package domain

import "errors"

var (
	ErrValidation             = errors.New("validation failed")
	ErrInvalidSpaceKey        = errors.New("invalid space key")
	ErrInvalidPolicy          = errors.New("invalid comment policy")
	ErrInvalidResource        = errors.New("invalid resource reference")
	ErrInvalidCommentContent  = errors.New("invalid comment content")
	ErrInvalidPlacement       = errors.New("invalid comment placement")
	ErrCrossThreadParent      = errors.New("parent belongs to another thread")
	ErrMaxDepthExceeded       = errors.New("maximum comment depth exceeded")
	ErrImagesDisabled         = errors.New("images are disabled")
	ErrLinksDisabled          = errors.New("links are disabled")
	ErrInvalidAttachment      = errors.New("invalid attachment")
	ErrInvalidOutboxEvent     = errors.New("invalid outbox event")
	ErrInvalidRealtimeTicket  = errors.New("invalid realtime ticket")
	ErrNotFound               = errors.New("not found")
	ErrConflict               = errors.New("conflict")
	ErrAuthenticationRequired = errors.New("authentication required")
	ErrAccessRequired         = errors.New("comment access required")
	ErrForbidden              = errors.New("comment operation forbidden")
	ErrThreadNotWritable      = errors.New("thread is not writable")
	ErrEditConflict           = errors.New("comment edit conflict")
	ErrIdempotencyConflict    = errors.New("idempotency key conflict")
	ErrSpaceNotFound          = errors.New("space not found")
	ErrThreadNotFound         = errors.New("thread not found")
	ErrCommentNotFound        = errors.New("comment not found")
	ErrParentNotFound         = errors.New("parent not found")
	ErrAttachmentNotFound     = errors.New("attachment not found")
	ErrAttachmentNotReady     = errors.New("attachment is not ready")
	ErrRealtimeTicketInvalid  = errors.New("realtime ticket is invalid or expired")
)
